### PR TITLE
8.1.0

### PR DESCRIPTION
**Pull request by imonroe**

### CODE REVIEW

**Comment by sherakama** [comment]
That may be a bug with the 'Engineering' default for line1. Let me build and validate.

**Comment by sherakama** [comment]
I don't think this is a blocker for release but let's get it sorted out what it is first.

**Comment by sherakama** [comment]
Tests pass on local...

**Comment by sherakama** [comment]
Second time through they don't

**Comment by sherakama** [comment]
Ah, one test turns off the block.

**Comment by sherakama** [comment]
OOO issue.

**Comment by sherakama** [comment]
https://github.com/SU-SOE/soe_profile/pull/66

**Comment by sherakama** [comment]
I think we can allow this to pass & merge knowing we have fixes for the tests out there.

**Comment by sherakama** [comment]
@imonroe @pookmish

**Comment by imonroe** [comment]
I'm ok with that, but I'm going to let @sherakama push the button, since I don't want to have broken tests on my approval.  :)

**Comment by pookmish** [comment]
We've decided to not allow merging at all with failing tests.

**Comment by sherakama** [comment]
@pookmish objections?

**Comment by sherakama** [comment]
Ok, let's do it then.

**Comment by pookmish** [comment]
Closing this to allow a new release branch to be created with the latest commit.

**Pull request closed without merging**
