### PR TITLE
D8CORE-1698: Config Sync Install Version

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR FIRST REVIEW

# Summary
- Adds some missing dotfiles like `.codeclimate.yml`
- Moves all of the configurations to the `sync` dir
- Updates and syncs many files with what is in stanford_profile

# Review By (Date)
- April 2nd

# Urgency
- High

# Steps to Test

1. Review the code and look for oddities, irregularities, or potential issues
2. To test this profile you can follow the steps in https://github.com/SU-SWS/acsf-lelandd8/pull/10
3. You can also test the BLT build on https://www.dev-cardinalsites.acsitefactory.com/ `D8CORE-1698-build`

# Affected Projects or Products
- D8CORE
- Stanford Profile
- Leland D8
- SOE

# Associated Issues and/or People
-  D8CORE-1698

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
@boznik ping.

**Comment by boznik** [comment]
Stanford Text Editor and Stanford News both need: 

CKEditor Accessibility Checker, CKEditor Balloon Panel

**Comment by sherakama** [comment]
@boznik please re-review.

**Comment by jbickar** [comment]
@boznik he was _listening to our 1:1_

**Comment by sherakama** [comment]
Yay, thank you.

**Pull request merged**
