### PR TITLE
D8CORE-580: Add seckit

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- Enable SecKit at install time.

# Needed By (Date)
- Whenever this stack goes into production

# Criticality
- How critical is this PR on a 1-10 scale? 4/10
- ISO would like HSTS on all websites

# Steps to Test

1. Check out this branch
2. Create a new site
3. Request a page from your new site and ensure that the `strict-transport-security: max-age=31536000` header is set.
4. Run the included Behat test.

# Affected Projects or Products
- D8CORE, Jackalope

# Associated Issues and/or People
- JIRA ticket: D8CORE-580
- Other PRs:
    - https://github.com/SU-SWS/acsf-cardinalsites/pull/48
    - https://github.com/SU-SWS/stanford_profile/pull/55
    - https://github.com/SU-SWS/acsf-lelandd8/pull/4
    - https://github.com/SU-SWS/acsf-lelandd8/pull/8

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
@boznik ping!

**Comment by boznik** [comment]
@jbickar this profile has already added seckit, but i see a pr asking to move this to the stack repo:

https://github.com/SU-SWS/acsf-lelandd8/pull/5

should the seckit dependency be removed from this profile?

**Comment by jbickar** [comment]
Is it bad to have it in `composer.json` in both? I'm not clear what our practice is.

**Comment by boznik** [comment]
@sherakama do you have an opinion on this?

**Comment by sherakama** [comment]
Projects should only declare their dependencies. If the dependency and config is going into the stanford_profile stack then it should not be needed here.

**Comment by boznik** [comment]
the dependency and settings are going into the stack, so my vote is to remove it from this profile. see:

https://github.com/SU-SWS/acsf-lelandd8/pull/5

**Comment by jbickar** [comment]
If it's being enabled here, then I think it belongs in the `composer.json` here. Unless you think it should be enabled in the stack instead.

**Comment by boznik** [comment]
yes, i just left a comment in that other pr to enable it in the stack where the settings live

**Comment by jbickar** [comment]
Enabling in the stack. See https://github.com/SU-SWS/acsf-lelandd8/pull/5

**Comment by jbickar** [comment]
I don't want to delete this branch until https://github.com/SU-SWS/acsf-lelandd8/pull/5 is merged.

**Comment by jbickar** [comment]
@boznik, ready for review again. See also https://github.com/SU-SWS/acsf-lelandd8/pull/8

**Comment by jbickar** [comment]
Whew, confusing. This is ready for review now, @boznik.

**Comment by boznik** [comment]
having issues with running the behat test. might be my config

**Comment by boznik** [comment]
behat test passed.

**Pull request merged**
