### PR TITLE
D8CORE-1609: Sync super footer/global messages from stanford_profile

### PR DESCRIPTION
**Pull request by sherakama**
# READY

# Summary
- Sync config from stanford_profile
- Update tests
- Upgrade paths for things that need them

# Test

1. Do a full build with this profile and review for errors (in terminal logs and visual checks on build)
2. Copy an existing site's database down from production (bioe is a good one) and import it then run database updates & config import
3. Or, review the sites on [LelandD8 Test](https://www.test-cardinalsites.acsitefactory.com/sites-by-group/grid?field_codebase_value=4&nodes=&users=&custom_theme_count=&disk_space=&pageviews_lastmonth=&pageviews=&visits_lastmonth=&visits=&field_domain_contains=&field_domain_value_1=&uid=) as they have the upgrade code ran on them.

### CODE REVIEW

**Comment by sherakama** [comment]
@imonroe FYI this PR exists as a starting point to sync from stanford_profile.

**Comment by sherakama** [comment]
Finally, green lights.

**Comment by imonroe** [comment]
so. many. configs.

**Review by imonroe — APPROVED** [review]
Looks good, as soon as it goes green with the composer change.

**Comment by sherakama** [comment]
> so. many. configs.

Imagine all of that as upgrade hooks tho?

**Pull request merged**
