### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by boznik** [comment]
yep, that could be it.

**Comment by boznik** [comment]
let me know if you want me to test.

**Comment by sherakama** [comment]
Totally is it. Tried it out on my local and this branch works.

Learned a few things about composer and autoloading through this debug. In /vendor/composer/autoload_static.php you can see the namespaces and directories for most things. I am not sure but it looks like the autoload setting in composer.json takes precedent over the namespace in the PHP file.

**Comment by sherakama** [comment]
I am going to build on this and re-sync the profile with the stuff that is in stanford_profile before a review is needed.

**Pull request closed without merging**
