### PR TITLE
D8CORE-2149: Updated tests and sync with stanford_profile.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Removes behat tests and syncs new codeception tests from stanford_profile.
- Original PR and work is here: https://github.com/SU-SWS/stanford_profile/pull/228

# Needed By (Date)
- Next release would be nice

# Urgency
- Low

# Steps to Test

1. Run tests
2. Wait 
4. Wait some more
7. Confirm green lights.

# Affected Projects or Products
- SOE 

# Associated Issues and/or People
- D8CORE-2149

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Tests pass!

**Comment by sherakama** [comment]
Thanks @pookmish for this work.

**Comment by boznik** [comment]
reviewing

**Comment by boznik** [comment]
1) WYSIWYGCest: Test filtered html
 Test  ../docroot/profiles/custom/soe_profile/tests/codeception/functional/Paragraphs/WYSIWYGCest.php:testFilteredHtml
 Step  Cant see element "address"
 Fail  Failed asserting that an array is empty.

**Comment by imonroe** [comment]
> 1. WYSIWYGCest: Test filtered html
>    Test  ../docroot/profiles/custom/soe_profile/tests/codeception/functional/Paragraphs/WYSIWYGCest.php:testFilteredHtml
>    Step  Cant see element "address"
>    Fail  Failed asserting that an array is empty.

How did you get it to fail?  It tests green in this branch?

**Comment by boznik** [comment]
It failed on my local after a fresh install. not sure why, since it is passing here.

**Comment by imonroe** [comment]
> It failed on my local after a fresh install. not sure why, since it is passing here.

Ok.  In that case, I'm going to approve and merge, since I can't reproduce the failure.

**Pull request merged**
