### PR TITLE
Update HomePageCest.php

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

### CODE REVIEW

**Comment by boznik** [comment]
@sherakama did you want to merge this into base or D8CORE-1989 ?

**Comment by sherakama** [comment]
8.x-1.x is fine.

**Comment by boznik** [comment]
This test is working now. There are three other failures. should i make a separate ticket to review the differences with stanford_profile and update/fix them?

three failures:

1) BasicPageParagraphsCest: Test card paragraph
 Test  ../docroot/profiles/custom/soe_profile/tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php:testCardParagraph
 Step  Can see "Superhead text"
 Fail  Failed asserting that  on page /test-cards

 2) BasicPageParagraphsCest: Test card paragraph
 Test  ../docroot/profiles/custom/soe_profile/tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php:testCardParagraph
 Step  Can see "Headline"
 Fail  Failed asserting that  on page /test-cards

 3) BasicPageParagraphsCest: Test card paragraph
 Test  ../docroot/profiles/custom/soe_profile/tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php:testCardParagraph
 Step  Can see link "Google Link","http://google.com/"
 Fail  No links containing text 'Google Link' were found in page /test-cards

**Comment by sherakama** [comment]
Sure, create a ticket and assign it to me. Circle isn't running automagically on this repo yet and I want to talk to Ian about that. That could be a good task for him. Code freeze isn't until the 11th so we have some time to get to it. If you want to just copy over everything in the `/test` folder from stanford_profile and run it on the soe_profile I would expect passing tests. Either way, don't spend much time on it.

**Pull request merged**
